### ISSUE TITLE
iPhone

### ISSUE THREAD

**Issue by sibinsavio** [EdJoPaTo/iPhoneBatteryHealth#8]
Battery health is decreasing and stood at 72%. But get almost 3:30 minutes of use in a single charge.

**Comment by EdJoPaTo** [comment]
Interesting for this list would be the exact iPhone Model and its Battery Start Date.

72% sounds way lower than most of the devices the list contains currently. Sounds like its worth it to get the battery replaced so the device can be easily used longer.

**Comment by sibinsavio** [comment]
Is there any way to make iPhone to consume less power?

**Comment by sibinsavio** [comment]
Without replacing the battery , is there any way to calibrate and increase the battery health ?

**Comment by EdJoPaTo** [comment]
Personally I mostly trust Apples Support pages on battery stuff as there are many strange information out there. Also Lithium Ion Batteries can have variations so Apple should know their own batteries best.
https://www.apple.com/batteries/

There are also listed some ways to maximize battery performance for example.

**Comment by sibinsavio** [comment]
I still have over 85 Gb of storage left , but the battery health didn't affect the performance speed. 
I need to know at what percentage I have to charge my iPhone ?
